import webscraping as ws

countryCode = ['en', 'br']#, 'it', 'es', 'de', 'fr'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ] #

for country in countryCode:
    ws.MatchHistory(country).update()
    ws.Standings(country).update()
    ws.Squads(country).update()
    ws.CompileData(country)
    ws.ProcessData(country, 'standings')
    ws.ProcessData(country, 'match_history')
    ws.ProcessData(country, 'squads')
